1. Импортируйте numpy под именем np

In [2]:
import numpy as np

2. Создайте одномерный массив ndarray arr1 размера 10, заполненный нулями.

In [3]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Создайте двумерный массив ndarray arr2 размера 5x10, заполненный единицами.

In [4]:
arr2 = np.ones((5, 10))
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

4. Замените в массиве arr2 4-й элемент в 3-й строке на 2.

In [5]:
arr2[2, 3] = 2
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Создайте одномерный массив ndarray arr3 с последовтельными числами от 50 до 100 включительно.


In [6]:
arr3 = np.arange(50, 101)
arr3

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

6. Переверните массив arr3.

In [7]:
np.flip(arr3)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50])

7. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [8]:
l = [1, 2, 0, 0, 4, 0]
finder = np.asarray(l)
np.where(finder != 0)

(array([0, 1, 4], dtype=int64),)

8. Создать двумерный массив ndarray размера 10x10, заполненный по строкам последовательными числами от 1 до 100.

In [9]:
ar = np.arange(1, 101)
np.reshape(ar, (10, 10))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

9. Создайте трехмерный массив arr4, заполненный случайными значениями.

In [10]:
arr4 = np.random.rand(5, 5, 5)
arr4

array([[[0.29619707, 0.06709057, 0.24490359, 0.26523422, 0.73995259],
        [0.35239512, 0.10253867, 0.07255835, 0.15559366, 0.70862495],
        [0.0774046 , 0.97354509, 0.36183589, 0.09522535, 0.3220482 ],
        [0.71891948, 0.78900601, 0.57302609, 0.92327465, 0.56290581],
        [0.73138736, 0.02520897, 0.41837788, 0.43454266, 0.29412714]],

       [[0.1415177 , 0.5233897 , 0.08348752, 0.26049343, 0.03310038],
        [0.22868433, 0.88515715, 0.89102595, 0.07808828, 0.63460083],
        [0.82220215, 0.58395685, 0.2324934 , 0.56602039, 0.30907261],
        [0.25725465, 0.23480097, 0.39913785, 0.66642006, 0.40314865],
        [0.86775226, 0.58627429, 0.03154334, 0.67330829, 0.57591287]],

       [[0.33909619, 0.82631058, 0.1290164 , 0.57546263, 0.94351089],
        [0.29294348, 0.2663778 , 0.72533159, 0.10657505, 0.22012681],
        [0.29155303, 0.06206456, 0.91973352, 0.74574253, 0.77002326],
        [0.76741352, 0.58562618, 0.3643122 , 0.61369306, 0.89451603],
        [0.55672

10. Найдите минимум и максимум в arr4.

In [11]:
print(np.min(arr4))
print(np.max(arr4))

0.0252089741707624
0.9861065348377895


11. Найдите среднее значение и стандартное отклонение в arr4.

In [12]:
print(np.mean(arr4))
print(np.std(arr4))

0.45810522763043293
0.27699147895583515


12. Создайте две неквадратные матрицы, заполните из случайными числами и перемножьте их

In [13]:
m1 = np.random.rand(5, 3)
m2 = np.random.rand(3, 5)

np.matmul(m1, m2)

array([[0.25458533, 0.25351311, 0.61593113, 0.67731967, 0.19480793],
       [0.27770952, 0.30235018, 0.67827328, 0.5713745 , 0.32800633],
       [0.43916985, 0.43949118, 1.08591949, 0.82740479, 0.49385675],
       [0.43462555, 0.5595366 , 1.03005162, 1.08953195, 0.557489  ],
       [0.34287825, 0.4886201 , 0.80856231, 0.77834476, 0.54907874]])

13. Создайте два случайных вектора и найдите их скалярное произведение.

In [14]:
v1 = np.random.rand(2)
v2 = np.random.rand(2)

np.dot(v1, v2)

0.3119269538688776

14. Отсортируйте случайный вектор.

In [15]:
import random

v = np.random.rand(random.randint(10, 20))
np.sort(v)

array([0.02827827, 0.08499188, 0.09322723, 0.10635858, 0.11387451,
       0.1415719 , 0.23322601, 0.29504932, 0.5654414 , 0.61368895,
       0.77890647, 0.79956179, 0.83006038, 0.94623514])

15. Проверьте, одинаковы ли два массива.

In [16]:
ar1 = np.random.rand(5)
ar2 = np.random.rand(5)

np.array_equal(ar1, ar2)

False

16. Создайте массив из координат 10 точек на плоскости. Преобразуйте эти координаты в полярные.

In [17]:
arrr = np.random.rand(10, 2)
x,y = arrr[:,0], arrr[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)

print(r)
print(t)

[1.14759731 0.44022715 0.70751562 0.48633259 0.68971567 0.66340841
 0.94351748 1.13978869 1.02909989 0.14046396]
[0.74508049 0.15304466 0.06730559 1.01902684 0.21709214 0.50519806
 0.09699669 0.64086816 0.45964927 0.1100617 ]


17. Преобразуйте массив из int во float

In [18]:
arr = np.arange(0, 100)
arr = arr.astype(float)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

18. Найти диагональные элементы произведения двух квадратных матриц.

In [20]:
m3x3_1 = np.random.rand(3, 3)
m3x3_2 = np.random.rand(3, 3)

res = np.matmul(m3x3_1, m3x3_2)
print(res)
np.diagonal(res)

[[0.72180308 0.24937787 0.27236626]
 [1.0176852  0.87012089 0.58856335]
 [0.18495114 0.2684569  0.27589044]]


array([0.72180308, 0.87012089, 0.27589044])

19. Создайте случайный двумерный массив, элементы которого распределены нормально с ненулевым средним и неединичным стандартным отклонением.
Вычтите из каждого элемента среднее и поделите этот элемент на его стандартное отклонение.
Вычислите среднее и стандартное отклонение получившегося массива.

In [2]:
import numpy as np
import random

# ar = np.asarray([random.randint(0, 5) for i in range(100)])
ar = np.random.normal(5, 2, 1000)
# ar = np.reshape(ar, (10, 10))
print(ar)
print(np.std(ar))
print(np.mean(ar))

[ 4.89114845  6.34718179  1.19414143  4.6938861   4.86300313  5.98986657
  5.03194545  3.5853461   6.59976633  5.46898017  8.40425992  4.62610271
  5.96079344  7.5923808   4.51190966  7.03442027  3.48500404  8.86181201
  5.44815552  4.95314818  5.47961298  7.69872727  5.3540815   3.43243525
  7.18733722  5.88021652  4.54695537  6.48074413  5.07931157  6.7214109
  4.03361525  8.254772    4.44771608  0.7396387   2.2519475   4.23309138
  4.82881393  3.87559157  5.77502135  4.29324334  3.38485244  4.22243662
  1.93673847  7.88890963  4.35456732  4.42279797  2.25078943  9.49903295
  4.82745052  6.8629576  10.61942037  6.80874229  2.35894479  5.40875368
  5.91109964  5.80317212  4.7495383   6.20428694  5.72841465  4.07903482
  3.47401798  4.47613144  1.68383776  8.57008264  6.76800949  2.75141673
  3.49401132  3.49972534  4.68614166  4.80727907  5.91757203  4.03616674
  6.20795366  5.37264261  4.36727444  2.32208666  6.08806804  5.84711364
  3.89748398  5.20115688  6.20582107  5.16988447  2.

In [3]:
ar = (ar - np.mean(ar)) / np.std(ar)
print(ar)
print(np.std(ar))
print(np.mean(ar))

[-8.98555331e-02  6.24829131e-01 -1.90450782e+00 -1.86680498e-01
 -1.03670485e-01  4.49443237e-01 -2.07462274e-02 -7.30800278e-01
  7.48808638e-01  1.93769473e-01  1.63453280e+00 -2.19951543e-01
  4.35172876e-01  1.23602712e+00 -2.76002471e-01  9.62155749e-01
 -7.80052540e-01  1.85911932e+00  1.83547827e-01 -5.94233616e-02
  1.98988522e-01  1.28822660e+00  1.37372195e-01 -8.05855592e-01
  1.03721406e+00  3.95622213e-01 -2.58800508e-01  6.90387355e-01
  2.50312931e-03  8.08517100e-01 -5.10770228e-01  1.56115760e+00
 -3.07511482e-01 -2.12759758e+00 -1.38529047e+00 -4.12858644e-01
 -1.20452036e-01 -5.88335142e-01  3.43987832e-01 -3.83333441e-01
 -8.29211310e-01 -4.18088466e-01 -1.54000880e+00  1.38157640e+00
 -3.53232954e-01 -3.19742378e-01 -1.38585890e+00  2.17189515e+00
 -1.21121256e-01  8.77994393e-01  2.72183016e+00  8.51383155e-01
 -1.33277153e+00  1.64207687e-01  4.10780995e-01  3.57805459e-01
 -1.59363970e-01  5.54690107e-01  3.21111230e-01 -4.88476325e-01
 -7.85444977e-01 -2.93563